# Essential macOS tools. Node and Bun are installed by scripts/shell.sh.
brew "bat"
brew "diff-so-fancy"
brew "direnv"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "gitleaks"
brew "htop"
brew "jq"
brew "python"
brew "ripgrep"
brew "tmux"
brew "tree"

cask "codex"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "kitty"
cask "raycast"
cask "zed"
